api:
  url: http://localhost:8080/employees

logging:
  level: INFO
  loggers:
    com.employee.app: INFO

  appenders:
    - type: console
      threshold: INFO
      logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"
      timeZone: UTC
