api:
  url: http://localhost:8080/employees

jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.employee.app: INFO
  appenders:
    - type: console
      threshold: INFO
      logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"
      timeZone: UTC
